### ISSUE TITLE
Allow passing in a decode coordinate transformation function

### ISSUE THREAD

**Issue by axrs** [mgaare/clojure-polyline#2]
We use the `clojure-polyline` decode function to transform some encoded polylines for further processing as GeoJSON structures. By default, Google's Javascripts implementation will decode a LineString into {:lng x :lat y} values (just like the `vec->coords` function. It would be great to be able to provide our own transform fn in to control the output of the coordinates. 

```clojure
(defn decode [polystring]
  (let [poly-ints (map #(- % 63) (map int polystring))
        poly-chunks (split poly-ints)
        decoded-chunks (map decode-chunk poly-chunks)]
    (->> decoded-chunks (map double) (partition 2) (combiner +)
         (vec->coords))))
```

To become something like this:

```clojure
(defn decode 
  ([polystring] (decode polystring vec->coords))
  ([polystring trans-f]
   (let [poly-ints (map #(- % 63) (map int polystring))
         poly-chunks (split poly-ints)
         decoded-chunks (map decode-chunk poly-chunks)]
     (->> decoded-chunks (map double) (partition 2) (combiner +)
          (trans-f)))))
```

I'm happy to do a PR if you agree with the change.

**Comment by mgaare** [comment]
I was looking at the API, and one thing that bothers me is that it's asymmetric. The `encode` function takes a collection of `[lat long]` vectors, but `decode` returns a collection of `{:latitude lat :longitude long}` maps. What I'm thinking for version 0.4.0 (I just released 0.3.0 with some major refactoring and performance improvements for encoding) is to go ahead and break the old API contract and have `decode` return '[lat long]` vectors too.

That way you could take the output of `decode` and do something like,
```
(->> (decode polystring)
    (map (fn [[lat long]] {:lat lat :lng long})))
```

or whatever transformation you want.

Would that work?

**Comment by mgaare** [comment]
The latest push to master does this. Haven't released it. Take a look and let me know what you think.

**Comment by axrs** [comment]
The new changes work well. The only change we had to make to support our structures was to reverse the results (from `[lat long]` to `[long lat]` for GeoJSON see [lonlat](https://macwright.org/lonlat/)). Otherwise the performance and simplicity works for us.

**Comment by mgaare** [comment]
I did a little bit of reworking to make your flow maybe a little nicer, and got some improvements out of it. Both decoding and encoding were refactored to each be a single transducer stack, and these transducers were assigned to symbols - `encoder` for encoding, `decoder` for decoding. I also added a `lonlat` utility function that flips `[lat lon]` to `[lon lat]`.

These changes mean you can do something like:
```
(into [] (comp decoder lonlat) your-polystring)
```
That will return the coords in `[lat lon]` format.

Going to cut a release and update the readme soon.
